/* ============================================================
   INVEST NAVIGATOR — OFFERS DATA
   ============================================================ */

/* ----------------------------------------------------------
   UZS BANK DEPOSITS
---------------------------------------------------------- */
const DEPOSIT_UZS_OFFERS = [
  { id: "uzs-asaka-hayot", provider: "Asaka Bank", providerCode: "AS",
    name: { uz: "Hayot depoziti", ru: "Депозит «Хайот»", en: "Hayot deposit" },
    rate: 18, term: 12, minUZS: 1000000,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/asakabank" },
  { id: "uzs-nbu-tezkor", provider: "Milliy Bank (NBU)", providerCode: "NB",
    name: { uz: "Tezkor", ru: "Тезкор", en: "Tezkor" },
    rate: 18, term: 6, minUZS: 500000,
    capitalization: "end", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/nbu" },
  { id: "uzs-agrobank-hosil", provider: "Agrobank", providerCode: "AG",
    name: { uz: "Hosil", ru: "Хосил", en: "Hosil" },
    rate: 21, term: 12, minUZS: 1000000,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/agrobank" },
  { id: "uzs-aloqabank-plus", provider: "Aloqabank", providerCode: "AL",
    name: { uz: "Aloqa Plus", ru: "Алока Плюс", en: "Aloqa Plus" },
    rate: 19, term: 24, minUZS: 5000000,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/aloqabank" },
  { id: "uzs-tbc-online", provider: "TBC Bank UZ", providerCode: "TB",
    name: { uz: "TBC Online", ru: "TBC Онлайн", en: "TBC Online" },
    rate: 21, term: 12, minUZS: 1000000,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/tbc" },
  { id: "uzs-tenge-online", provider: "Tenge Bank", providerCode: "TG",
    name: { uz: "Tenge Online", ru: "Tenge Online", en: "Tenge Online" },
    rate: 18, term: 12, minUZS: 1000000,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/tenge" },
  { id: "uzs-turon-klassik", provider: "Turonbank", providerCode: "TU",
    name: { uz: "Turon Klassik", ru: "Турон Классик", en: "Turon Classic" },
    rate: 18, term: 12, minUZS: 1000000,
    capitalization: "end", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/turonbank" },
];

/* ----------------------------------------------------------
   USD BANK DEPOSITS
---------------------------------------------------------- */
const DEPOSIT_USD_OFFERS = [
  { id: "usd-asaka-valyuta", provider: "Asaka Bank", providerCode: "AS",
    name: { uz: "Valyuta depoziti", ru: "Валютный депозит", en: "FX deposit" },
    rate: 6, term: 24, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/asakabank" },
  { id: "usd-nbu-stabil", provider: "Milliy Bank (NBU)", providerCode: "NB",
    name: { uz: "Stabil USD", ru: "Стабиль USD", en: "Stable USD" },
    rate: 5, term: 12, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/nbu" },
  { id: "usd-aloqa-classic", provider: "Aloqabank", providerCode: "AL",
    name: { uz: "Aloqa Classic", ru: "Алока Classic", en: "Aloqa Classic" },
    rate: 6, term: 24, minUSD: 500,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/aloqabank" },
  { id: "usd-kapital-valyuta", provider: "Kapitalbank", providerCode: "KP",
    name: { uz: "Valyuta", ru: "Валюта", en: "Currency" },
    rate: 4, term: 12, minUSD: 100,
    capitalization: "end", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/kapitalbank" },
  { id: "usd-tbc-online", provider: "TBC Bank UZ", providerCode: "TB",
    name: { uz: "TBC USD", ru: "TBC USD", en: "TBC USD" },
    rate: 5, term: 12, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/tbc" },
  { id: "usd-garant-stabil", provider: "Garant Bank", providerCode: "GR",
    name: { uz: "Garant USD", ru: "Гарант USD", en: "Garant USD" },
    rate: 8, term: 13, minUSD: 5000,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/garantbank" },
];

/* ----------------------------------------------------------
   TSE STOCKS
---------------------------------------------------------- */
const TSE_OFFERS = [
  { id: "tse-uznif", ticker: "UZNIF",
    name: { uz: "O'zbekiston Milliy Investitsiya Fondi", ru: "Узб. нац. инвест. фонд", en: "Uzbek National Investment Fund" },
    sector: "fund", priceUZS: 1280, marketCapB: 800, divYield: 0, change30d: 8.5,
    liq: "hi", ipo: "2024-12", url: "https://uzse.uz/issuer/uznif" },
  { id: "tse-hmkb", ticker: "HMKB",
    name: { uz: "Hamkorbank", ru: "Хамкорбанк", en: "Hamkorbank" },
    sector: "bank", priceUZS: 1450, marketCapB: 2400, divYield: 6.2, change30d: 5.8,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/hmkb" },
  { id: "tse-sqbn", ticker: "SQBN",
    name: { uz: "Sanoatqurilishbank", ru: "Саноаткурилишбанк", en: "Sanoatqurilishbank" },
    sector: "bank", priceUZS: 980, marketCapB: 1850, divYield: 5.5, change30d: 2.1,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/sqbn" },
  { id: "tse-agbn", ticker: "AGBN",
    name: { uz: "Agrobank", ru: "Агробанк", en: "Agrobank" },
    sector: "bank", priceUZS: 720, marketCapB: 980, divYield: 4.8, change30d: 1.4,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/agbn" },
  { id: "tse-umkk", ticker: "UMKK",
    name: { uz: "O'zmetkombinat", ru: "Узметкомбинат", en: "Uzmetkombinat" },
    sector: "metals", priceUZS: 4200, marketCapB: 540, divYield: 7.2, change30d: -2.5,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/umkk" },
  { id: "tse-ungp", ticker: "UNGP",
    name: { uz: "O'zbekneftegaz", ru: "Узбекнефтегаз", en: "Uzbekneftegaz" },
    sector: "energy", priceUZS: 6200, marketCapB: 1620, divYield: 8.0, change30d: 6.4,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/ungp" },
  { id: "tse-agmk", ticker: "AGMK",
    name: { uz: "Olmaliq KMK", ru: "Алмалыкский ГМК", en: "Almalyk MMC" },
    sector: "metals", priceUZS: 24500, marketCapB: 2890, divYield: 9.2, change30d: 11.3,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/agmk" },
  { id: "tse-uzau", ticker: "UZAU",
    name: { uz: "Navoiy KMK", ru: "Навоийский ГМК", en: "Navoi MMC" },
    sector: "metals", priceUZS: 38500, marketCapB: 4250, divYield: 10.5, change30d: 14.2,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/uzau" },
  { id: "tse-kscm", ticker: "KSCM",
    name: { uz: "Quvasoy Sement", ru: "Кувасайцемент", en: "Quvasoy Cement" },
    sector: "cement", priceUZS: 8800, marketCapB: 210, divYield: 5.8, change30d: 4.1,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/kscm" },
  { id: "tse-chrg", ticker: "CHRG",
    name: { uz: "Chirchiq Kimyo", ru: "Чирчик Кимё", en: "Chirchiq Chemicals" },
    sector: "chemicals", priceUZS: 14200, marketCapB: 410, divYield: 6.8, change30d: 5.2,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/chrg" },
  { id: "tse-uzrt", ticker: "UZRT",
    name: { uz: "O'zbektelekom", ru: "Узбектелеком", en: "Uzbektelecom" },
    sector: "telecom", priceUZS: 3850, marketCapB: 720, divYield: 5.5, change30d: 1.8,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/uzrt" },
  { id: "tse-asbt", ticker: "ASBT",
    name: { uz: "Asaka Bank", ru: "Асака Банк", en: "Asaka Bank" },
    sector: "bank", priceUZS: 2100, marketCapB: 1980, divYield: 5.2, change30d: 4.4,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/asbt" },
];

/* ----------------------------------------------------------
   CRYPTO — TOP 10
   fields: ticker, name, network, priceUSD, marketCapB (USD),
           change30d (%), stakingAPY (%), rank
---------------------------------------------------------- */
const CRYPTO_OFFERS = [
  { id: "crypto-btc", ticker: "BTC",
    name: { uz: "Bitcoin", ru: "Bitcoin", en: "Bitcoin" },
    network: "bitcoin", priceUSD: 95800, marketCapB: 1880,
    change30d: 14.2, stakingAPY: 0, rank: 1,
    url: "https://coinmarketcap.com/currencies/bitcoin/" },
  { id: "crypto-eth", ticker: "ETH",
    name: { uz: "Ethereum", ru: "Ethereum", en: "Ethereum" },
    network: "ethereum", priceUSD: 3420, marketCapB: 411,
    change30d: 8.5, stakingAPY: 3.5, rank: 2,
    url: "https://coinmarketcap.com/currencies/ethereum/" },
  { id: "crypto-bnb", ticker: "BNB",
    name: { uz: "BNB", ru: "BNB", en: "BNB" },
    network: "bsc", priceUSD: 582, marketCapB: 85,
    change30d: 5.1, stakingAPY: 5.2, rank: 3,
    url: "https://coinmarketcap.com/currencies/bnb/" },
  { id: "crypto-sol", ticker: "SOL",
    name: { uz: "Solana", ru: "Solana", en: "Solana" },
    network: "solana", priceUSD: 182, marketCapB: 85,
    change30d: 22.4, stakingAPY: 7.1, rank: 4,
    url: "https://coinmarketcap.com/currencies/solana/" },
  { id: "crypto-xrp", ticker: "XRP",
    name: { uz: "XRP", ru: "XRP", en: "XRP" },
    network: "ripple", priceUSD: 0.54, marketCapB: 31,
    change30d: -3.2, stakingAPY: 0, rank: 5,
    url: "https://coinmarketcap.com/currencies/xrp/" },
  { id: "crypto-ton", ticker: "TON",
    name: { uz: "Toncoin", ru: "Toncoin", en: "Toncoin" },
    network: "ton", priceUSD: 5.5, marketCapB: 14,
    change30d: 6.9, stakingAPY: 5.5, rank: 9,
    url: "https://coinmarketcap.com/currencies/toncoin/" },
  { id: "crypto-ada", ticker: "ADA",
    name: { uz: "Cardano", ru: "Cardano", en: "Cardano" },
    network: "cardano", priceUSD: 0.45, marketCapB: 16,
    change30d: -1.8, stakingAPY: 4.5, rank: 8,
    url: "https://coinmarketcap.com/currencies/cardano/" },
  { id: "crypto-avax", ticker: "AVAX",
    name: { uz: "Avalanche", ru: "Avalanche", en: "Avalanche" },
    network: "avalanche", priceUSD: 33, marketCapB: 14,
    change30d: 9.7, stakingAPY: 8.2, rank: 11,
    url: "https://coinmarketcap.com/currencies/avalanche/" },
  { id: "crypto-dot", ticker: "DOT",
    name: { uz: "Polkadot", ru: "Polkadot", en: "Polkadot" },
    network: "polkadot", priceUSD: 6.9, marketCapB: 9,
    change30d: 4.3, stakingAPY: 12.5, rank: 14,
    url: "https://coinmarketcap.com/currencies/polkadot-new/" },
  { id: "crypto-link", ticker: "LINK",
    name: { uz: "Chainlink", ru: "Chainlink", en: "Chainlink" },
    network: "ethereum", priceUSD: 14.4, marketCapB: 8,
    change30d: 11.8, stakingAPY: 4.8, rank: 16,
    url: "https://coinmarketcap.com/currencies/chainlink/" },
];

/* ----------------------------------------------------------
   PRECIOUS STONES — TOP 10
   fields: stone, grade, color, weightLabel,
           priceUSD (per piece), change1y (%), liq
---------------------------------------------------------- */
const GEMS_OFFERS = [
  { id: "gem-diamond-1ct",
    name: { uz: "Brilliant 1 karat (D, VVS2)", ru: "Бриллиант 1 кар. (D, VVS2)", en: "Diamond 1ct (D, VVS2)" },
    stone: "diamond", grade: "VVS2", color: "D", weightLabel: "1.00 ct",
    priceUSD: 8500, change1y: 4.8, liq: "mid",
    url: "https://www.rapaport.com/" },
  { id: "gem-ruby-1ct",
    name: { uz: "Qizil yoqut 1 karat (Burma, qayta ishlanmagan)", ru: "Рубин 1 кар. (Бирма, необогр.)", en: "Ruby 1ct (Burma, unheated)" },
    stone: "ruby", grade: "AAA", color: "Pigeon Blood", weightLabel: "1.00 ct",
    priceUSD: 12000, change1y: 8.2, liq: "low",
    url: "https://www.gemval.com/" },
  { id: "gem-emerald-1ct",
    name: { uz: "Zumrad 1 karat (Kolumbiya)", ru: "Изумруд 1 кар. (Колумбия)", en: "Emerald 1ct (Colombia)" },
    stone: "emerald", grade: "AAA", color: "Vivid Green", weightLabel: "1.00 ct",
    priceUSD: 7200, change1y: 5.5, liq: "low",
    url: "https://www.gemval.com/" },
  { id: "gem-sapphire-1ct",
    name: { uz: "Ko'k yoqut 1 karat (Kashmir)", ru: "Сапфир 1 кар. (Кашмир)", en: "Sapphire 1ct (Kashmir)" },
    stone: "sapphire", grade: "AAA", color: "Royal Blue", weightLabel: "1.00 ct",
    priceUSD: 6800, change1y: 7.1, liq: "low",
    url: "https://www.gemval.com/" },
  { id: "gem-alexandrite-1ct",
    name: { uz: "Aleksandrit 1 karat (rang o'zgaruvchi)", ru: "Александрит 1 кар. (цветоменяющий)", en: "Alexandrite 1ct (color-change)" },
    stone: "alexandrite", grade: "AA", color: "Color-change", weightLabel: "1.00 ct",
    priceUSD: 15000, change1y: 12.4, liq: "low",
    url: "https://www.gemval.com/" },
  { id: "gem-spinel-1ct",
    name: { uz: "Qizil shpinel 1 karat", ru: "Красная шпинель 1 кар.", en: "Red Spinel 1ct" },
    stone: "spinel", grade: "AA", color: "Red", weightLabel: "1.00 ct",
    priceUSD: 3200, change1y: 9.6, liq: "low",
    url: "https://www.gemval.com/" },
  { id: "gem-tanzanite-1ct",
    name: { uz: "Tanzanit 1 karat", ru: "Танзанит 1 кар.", en: "Tanzanite 1ct" },
    stone: "tanzanite", grade: "AA", color: "Vivid Violet-Blue", weightLabel: "1.00 ct",
    priceUSD: 1800, change1y: 6.3, liq: "mid",
    url: "https://www.gemval.com/" },
  { id: "gem-tourmaline-1ct",
    name: { uz: "Paraiba turmalin 1 karat", ru: "Параиба-турмалин 1 кар.", en: "Paraiba Tourmaline 1ct" },
    stone: "tourmaline", grade: "AAA", color: "Neon Blue-Green", weightLabel: "1.00 ct",
    priceUSD: 9500, change1y: 11.2, liq: "low",
    url: "https://www.gemval.com/" },
  { id: "gem-opal-5ct",
    name: { uz: "Qora opal 5 karat (Avstraliya)", ru: "Чёрный опал 5 кар. (Австралия)", en: "Black Opal 5ct (Australia)" },
    stone: "opal", grade: "AA", color: "Black", weightLabel: "5.00 ct",
    priceUSD: 4500, change1y: 8.8, liq: "low",
    url: "https://www.gemval.com/" },
  { id: "gem-diamond-05ct",
    name: { uz: "Brilliant 0.5 karat (E, VS1)", ru: "Бриллиант 0.5 кар. (E, VS1)", en: "Diamond 0.5ct (E, VS1)" },
    stone: "diamond", grade: "VS1", color: "E", weightLabel: "0.50 ct",
    priceUSD: 2800, change1y: 3.5, liq: "mid",
    url: "https://www.rapaport.com/" },
];

/* ----------------------------------------------------------
   GAMING SKINS — CS2 (5) + Other games (5)
   fields: game, wear (cs2 only), priceUSD, change30d, float, platform
   wear: "fn" | "mw" | "ft" | "ww" | "bs" | null
   game: "cs2" | "dota2" | "tf2" | "rust" | "pubg"
---------------------------------------------------------- */
const GAMING_OFFERS = [
  /* ---- CS2 ---- */
  { id: "skin-cs2-ak-redline",
    name: { uz: "AK-47 | Redline (FT)", ru: "AK-47 | Redline (FT)", en: "AK-47 | Redline (FT)" },
    game: "cs2", wear: "ft", priceUSD: 24.5, change30d: 8.2, float: "0.27", platform: "steam",
    url: "https://steamcommunity.com/market/listings/730/AK-47%20%7C%20Redline%20%28Field-Tested%29" },
  { id: "skin-cs2-awp-asiimov",
    name: { uz: "AWP | Asiimov (FT)", ru: "AWP | Asiimov (FT)", en: "AWP | Asiimov (FT)" },
    game: "cs2", wear: "ft", priceUSD: 68.0, change30d: 12.5, float: "0.22", platform: "steam",
    url: "https://steamcommunity.com/market/listings/730/AWP%20%7C%20Asiimov%20%28Field-Tested%29" },
  { id: "skin-cs2-m4a4-howl",
    name: { uz: "M4A4 | Howl (MW)", ru: "M4A4 | Howl (MW)", en: "M4A4 | Howl (MW)" },
    game: "cs2", wear: "mw", priceUSD: 1850.0, change30d: 5.7, float: "0.09", platform: "steam",
    url: "https://steamcommunity.com/market/listings/730/M4A4%20%7C%20Howl%20%28Minimal%20Wear%29" },
  { id: "skin-cs2-karambit-doppler",
    name: { uz: "Karambit | Doppler (FN)", ru: "Karambit | Doppler (FN)", en: "Karambit | Doppler (FN)" },
    game: "cs2", wear: "fn", priceUSD: 920.0, change30d: -2.3, float: "0.01", platform: "steam",
    url: "https://steamcommunity.com/market/listings/730/%E2%98%85%20Karambit%20%7C%20Doppler%20%28Factory%20New%29" },
  { id: "skin-cs2-glock-fade",
    name: { uz: "Glock-18 | Fade (FN)", ru: "Glock-18 | Fade (FN)", en: "Glock-18 | Fade (FN)" },
    game: "cs2", wear: "fn", priceUSD: 185.0, change30d: 3.4, float: "0.02", platform: "steam",
    url: "https://steamcommunity.com/market/listings/730/Glock-18%20%7C%20Fade%20%28Factory%20New%29" },
  /* ---- Other games ---- */
  { id: "skin-dota2-manifold",
    name: { uz: "Manifold Paradox — PA Arcana", ru: "Manifold Paradox — PA Arcana", en: "Manifold Paradox — PA Arcana" },
    game: "dota2", wear: null, priceUSD: 32.0, change30d: 1.8, float: null, platform: "steam",
    url: "https://steamcommunity.com/market/listings/570/Manifold%20Paradox" },
  { id: "skin-tf2-burning",
    name: { uz: "TF2: Burning Flames Team Captain", ru: "TF2: Burning Flames Team Captain", en: "TF2: Burning Flames Team Captain" },
    game: "tf2", wear: null, priceUSD: 420.0, change30d: 6.2, float: null, platform: "steam",
    url: "https://steamcommunity.com/market/search?q=burning+flames+team+captain&appid=440" },
  { id: "skin-rust-ak",
    name: { uz: "Rust: AK47 Tempered", ru: "Rust: AK47 Tempered", en: "Rust: AK47 Tempered" },
    game: "rust", wear: null, priceUSD: 18.5, change30d: -1.2, float: null, platform: "steam",
    url: "https://steamcommunity.com/market/listings/252490/AK47%20Tempered" },
  { id: "skin-pubg-pan",
    name: { uz: "PUBG: Gold Mirado (avtomobil skin)", ru: "PUBG: Gold Mirado (скин авто)", en: "PUBG: Gold Mirado (vehicle skin)" },
    game: "pubg", wear: null, priceUSD: 45.0, change30d: 0.5, float: null, platform: "steam",
    url: "https://steamcommunity.com/market/search?q=gold+mirado&appid=578080" },
  { id: "skin-dota2-ultra",
    name: { uz: "Dota 2: Genuine Axe Immortal Set", ru: "Dota 2: Genuine Axe Immortal Set", en: "Dota 2: Genuine Axe Immortal Set" },
    game: "dota2", wear: null, priceUSD: 85.0, change30d: 4.1, float: null, platform: "steam",
    url: "https://steamcommunity.com/market/search?appid=570&q=immortal+axe" },
];

/* ----------------------------------------------------------
   PRECIOUS METALS — TOP 10
   fields: metal, symbol, priceUSD, unit ("oz"|"tonne"), change1y, liq, category
   category: "precious" | "industrial"
---------------------------------------------------------- */
const PRECIOUS_METALS_OFFERS = [
  { id: "metal-gold",
    name: { uz: "Oltin", ru: "Золото", en: "Gold" },
    metal: "gold", symbol: "Au", priceUSD: 2050, unit: "oz",
    change1y: 12.5, liq: "hi", category: "precious",
    url: "https://www.kitco.com/charts/gold" },
  { id: "metal-silver",
    name: { uz: "Kumush", ru: "Серебро", en: "Silver" },
    metal: "silver", symbol: "Ag", priceUSD: 24.8, unit: "oz",
    change1y: 8.2, liq: "hi", category: "precious",
    url: "https://www.kitco.com/charts/silver" },
  { id: "metal-platinum",
    name: { uz: "Platina", ru: "Платина", en: "Platinum" },
    metal: "platinum", symbol: "Pt", priceUSD: 952, unit: "oz",
    change1y: -5.3, liq: "mid", category: "precious",
    url: "https://www.kitco.com/charts/platinum" },
  { id: "metal-palladium",
    name: { uz: "Palladiy", ru: "Палладий", en: "Palladium" },
    metal: "palladium", symbol: "Pd", priceUSD: 1024, unit: "oz",
    change1y: -18.4, liq: "mid", category: "precious",
    url: "https://www.kitco.com/charts/palladium" },
  { id: "metal-rhodium",
    name: { uz: "Rodiy", ru: "Родий", en: "Rhodium" },
    metal: "rhodium", symbol: "Rh", priceUSD: 4500, unit: "oz",
    change1y: -22.0, liq: "low", category: "precious",
    url: "https://www.kitco.com/charts/rhodium" },
  { id: "metal-copper",
    name: { uz: "Mis (Bronza asosi)", ru: "Медь (основа бронзы)", en: "Copper (Bronze base)" },
    metal: "copper", symbol: "Cu", priceUSD: 8750, unit: "tonne",
    change1y: 6.8, liq: "hi", category: "industrial",
    url: "https://www.lme.com/en/metals/non-ferrous/lme-copper" },
  { id: "metal-aluminum",
    name: { uz: "Alyumin", ru: "Алюминий", en: "Aluminum" },
    metal: "aluminum", symbol: "Al", priceUSD: 2280, unit: "tonne",
    change1y: 3.2, liq: "hi", category: "industrial",
    url: "https://www.lme.com/en/metals/non-ferrous/lme-aluminium" },
  { id: "metal-nickel",
    name: { uz: "Nikel", ru: "Никель", en: "Nickel" },
    metal: "nickel", symbol: "Ni", priceUSD: 17500, unit: "tonne",
    change1y: -8.4, liq: "mid", category: "industrial",
    url: "https://www.lme.com/en/metals/non-ferrous/lme-nickel" },
  { id: "metal-titanium",
    name: { uz: "Titan", ru: "Титан", en: "Titanium" },
    metal: "titanium", symbol: "Ti", priceUSD: 11000, unit: "tonne",
    change1y: 4.1, liq: "low", category: "industrial",
    url: "https://www.metalary.com/titanium-price" },
  { id: "metal-cobalt",
    name: { uz: "Kobalt", ru: "Кобальт", en: "Cobalt" },
    metal: "cobalt", symbol: "Co", priceUSD: 33000, unit: "tonne",
    change1y: -12.6, liq: "mid", category: "industrial",
    url: "https://www.lme.com/en/metals/ev-battery-materials/lme-cobalt" },
];

/* ----------------------------------------------------------
   REGISTRY
---------------------------------------------------------- */
const OFFERS = {
  "deposit-uzs":    { kind: "deposit",         currency: "UZS", items: DEPOSIT_UZS_OFFERS },
  "deposit-usd":    { kind: "deposit",         currency: "USD", items: DEPOSIT_USD_OFFERS },
  "tse":            { kind: "stock",           currency: "UZS", items: TSE_OFFERS },
  "crypto":         { kind: "crypto",          currency: "USD", items: CRYPTO_OFFERS },
  "precious-metals":{ kind: "precious-metals", currency: "USD", items: PRECIOUS_METALS_OFFERS },
  "gems":           { kind: "gems",            currency: "USD", items: GEMS_OFFERS },
  "gaming":         { kind: "gaming",          currency: "USD", items: GAMING_OFFERS },
};

/* ----------------------------------------------------------
   I18N
---------------------------------------------------------- */
const OFFERS_I18N = {
  uz: {
    "back": "← Kategoriyalar",
    "detail.offers": "ta taklif",

    /* ---- deposit ---- */
    "dep.rate":  "Yillik foiz", "dep.term": "Muddat", "dep.min": "Min. summa",
    "dep.cap":   "Kapitalizatsiya", "dep.early": "Muddatdan oldin yechib olish",
    "dep.online":"Online ochish", "dep.bank": "Bank", "dep.month": "oy",
    "dep.cap.monthly": "Oylik kapitalizatsiya", "dep.cap.end": "Muddat oxirida",
    "dep.early.yes": "Erta yechib olish: ha", "dep.early.partial": "Erta yechib olish: qisman",
    "dep.early.no":  "Erta yechib olish: yo'q",
    "dep.sort.rate.desc":"Foiz: yuqoridan pastga", "dep.sort.rate.asc":"Foiz: pastdan yuqoriga",
    "dep.sort.term.asc":"Muddat: qisqadan uzunga", "dep.sort.term.desc":"Muddat: uzundan qisqaga",
    "dep.sort.min.asc":"Min. summa: kichikdan kattaga", "dep.sort.min.desc":"Min. summa: kattadan kichikka",
    "dep.tog.cap":"Kapitalizatsiya", "dep.tog.early":"Erta yechish", "dep.tog.online":"Online ochish",
    "dep.tog.all":"Barchasi", "dep.tog.monthly":"Oylik", "dep.tog.end":"Oxirida",
    "dep.tog.yes":"Ha", "dep.tog.partial":"Qisman", "dep.tog.no":"Yo'q",
    "dep.filter.bank.all":"Bank: barchasi", "dep.filter.term.all":"Muddat: har qanday",
    "dep.filter.term.6":"Muddat: 6 oygacha", "dep.filter.term.12":"Muddat: 12 oygacha",
    "dep.filter.term.24":"Muddat: 24 oygacha", "dep.filter.term.long":"Muddat: 24 oydan ko'p",
    "dep.search.ph":"Bank yoki depozit nomi…",

    /* ---- stock ---- */
    "stk.price":"Narx", "stk.cap":"Bozor kapital", "stk.div":"Dividend",
    "stk.change":"30 kun", "stk.sector":"Tarmoq", "stk.liq":"Likvidlik", "stk.ipo":"Yangi IPO",
    "stk.sort.div.desc":"Dividend: yuqoridan pastga", "stk.sort.div.asc":"Dividend: pastdan yuqoriga",
    "stk.sort.change.desc":"O'zgarish: yuqoridan pastga", "stk.sort.change.asc":"O'zgarish: pastdan yuqoriga",
    "stk.sort.cap.desc":"Kapital: kattadan kichikka", "stk.sort.cap.asc":"Kapital: kichikdan kattaga",
    "stk.sort.price.desc":"Narx: yuqoridan pastga", "stk.sort.price.asc":"Narx: pastdan yuqoriga",
    "stk.filter.sector.all":"Tarmoq: barchasi", "stk.filter.liq.all":"Likvidlik: har qanday",
    "stk.filter.div.all":"Dividend: har qanday", "stk.filter.div.yes":"Dividend bor",
    "stk.filter.div.no":"Dividendsiz",
    "stk.tog.dividend":"Dividend", "stk.tog.movement":"Harakat", "stk.tog.ipo":"Yangi IPO",
    "stk.tog.liq":"Likvidlik", "stk.tog.all":"Barchasi", "stk.tog.div.yes":"Bor",
    "stk.tog.div.no":"Yo'q", "stk.tog.up":"O'sgan", "stk.tog.down":"Tushgan",
    "stk.tog.ipo.yes":"Faqat yangi IPO", "stk.tog.liq.hi":"Yuqori",
    "stk.tog.liq.mid":"O'rta", "stk.tog.liq.low":"Past",
    "stk.search.ph":"Tiker yoki kompaniya nomi…",
    "sec.bank":"Bank", "sec.energy":"Energetika", "sec.metals":"Metallurgiya",
    "sec.cement":"Sement", "sec.telecom":"Telekom", "sec.industrial":"Sanoat",
    "sec.chemicals":"Kimyo", "sec.consumer":"Iste'mol", "sec.insurance":"Sug'urta", "sec.fund":"Fond",

    /* ---- crypto ---- */
    "crypt.search.ph":"Token yoki tarmoq nomi…",
    "crypt.sort.cap.desc":"Market cap: kattadan kichikka", "crypt.sort.cap.asc":"Market cap: kichikdan kattaga",
    "crypt.sort.price.desc":"Narx: yuqoridan pastga", "crypt.sort.price.asc":"Narx: pastdan yuqoriga",
    "crypt.sort.change.desc":"30k o'zgarish: yuqoridan", "crypt.sort.change.asc":"30k o'zgarish: pastdan",
    "crypt.sort.staking.desc":"Staking APY: yuqoridan", "crypt.filter.network.all":"Tarmoq: barchasi",
    "crypt.price":"Narx (USD)", "crypt.cap":"Market cap", "crypt.change":"30 kun",
    "crypt.staking":"Staking APY", "crypt.rank":"Reyting", "crypt.network":"Tarmoq",
    "crypt.tog.staking":"Staking", "crypt.tog.all":"Barchasi",
    "crypt.tog.staking.yes":"Bor", "crypt.tog.staking.no":"Yo'q",
    "go.crypto":"CoinMarketCap da ko'rish",
    "net.bitcoin":"Bitcoin", "net.ethereum":"Ethereum", "net.bsc":"BNB Chain",
    "net.solana":"Solana", "net.ripple":"Ripple", "net.cardano":"Cardano",
    "net.avalanche":"Avalanche", "net.polkadot":"Polkadot", "net.ton":"TON",
    "head.stat.bestToken":"Eng ko'p o'sgan",

    /* ---- precious metals ---- */
    "metal.search.ph":"Metall nomi yoki kimyoviy belgi…",
    "metal.sort.price.desc":"Narx: yuqoridan pastga", "metal.sort.price.asc":"Narx: pastdan yuqoriga",
    "metal.sort.change.desc":"1y o'zgarish: yuqoridan", "metal.sort.change.asc":"1y o'zgarish: pastdan",
    "metal.filter.cat.all":"Tur: barchasi",
    "metal.price":"Narx (USD)", "metal.change":"1 yil", "metal.symbol":"Belgi",
    "metal.category":"Tur", "metal.unit.oz":"troy oz", "metal.unit.tonne":"tonna",
    "metal.tog.liq":"Likvidlik", "metal.tog.all":"Barchasi",
    "metal.tog.liq.hi":"Yuqori", "metal.tog.liq.mid":"O'rta", "metal.tog.liq.low":"Past",
    "metal.tog.cat":"Tur", "metal.tog.cat.all":"Barchasi",
    "metal.cat.precious":"Qimmatbaho metall", "metal.cat.industrial":"Sanoat metalli",
    "go.metal":"Batafsil ma'lumot",
    "head.stat.bestMetal":"Eng ko'p o'sgan",

    /* ---- gems ---- */
    "gem.search.ph":"Tosh turi yoki nom…",
    "gem.sort.price.desc":"Narx: yuqoridan pastga", "gem.sort.price.asc":"Narx: pastdan yuqoriga",
    "gem.sort.change.desc":"1y o'zgarish: yuqoridan", "gem.sort.change.asc":"1y o'zgarish: pastdan",
    "gem.filter.stone.all":"Tosh: barchasi",
    "gem.price":"Narx ($/dona)", "gem.change":"1 yil", "gem.stone":"Tosh turi",
    "gem.grade":"Sifat", "gem.weight":"Og'irlik",
    "gem.tog.liq":"Likvidlik", "gem.tog.all":"Barchasi",
    "gem.tog.liq.hi":"Yuqori", "gem.tog.liq.mid":"O'rta", "gem.tog.liq.low":"Past",
    "stone.diamond":"Brilliant (Olmos)", "stone.ruby":"Qizil yoqut (Rubin)",
    "stone.emerald":"Zumrad (Izumrud)", "stone.sapphire":"Ko'k yoqut (Sapfir)",
    "stone.alexandrite":"Aleksandrit", "stone.spinel":"Shpinel",
    "stone.tanzanite":"Tanzanit", "stone.tourmaline":"Turmalin (Paraiba)",
    "stone.opal":"Qora opal",
    "go.gems":"Batafsil ma'lumot",
    "head.stat.bestGem":"Eng ko'p o'sgan",

    /* ---- gaming ---- */
    "skin.search.ph":"Item yoki o'yin nomi…",
    "skin.sort.price.desc":"Narx: yuqoridan pastga", "skin.sort.price.asc":"Narx: pastdan yuqoriga",
    "skin.sort.change.desc":"30k o'zgarish: yuqoridan", "skin.sort.change.asc":"30k o'zgarish: pastdan",
    "skin.filter.game.all":"O'yin: barchasi",
    "skin.price":"Steam narxi (USD)", "skin.change":"30 kun",
    "skin.game":"O'yin", "skin.wear":"Holat", "skin.float":"Float",
    "skin.tog.game":"O'yin", "skin.tog.wear":"Holat", "skin.tog.all":"Barchasi",
    "skin.tog.cs2":"CS2", "skin.tog.other":"Boshqa",
    "game.cs2":"CS2", "game.dota2":"Dota 2",
    "game.tf2":"TF2", "game.rust":"Rust", "game.pubg":"PUBG",
    "wear.fn":"Factory New", "wear.mw":"Minimal Wear",
    "wear.ft":"Field-Tested", "wear.ww":"Well-Worn", "wear.bs":"Battle-Scarred",
    "go.skin":"Steam Market da ko'rish",
    "head.stat.bestSkin":"Eng ko'p o'sgan",

    /* ---- shared ---- */
    "go.bank":"bank.uz da ochish", "go.stock":"uzse.uz da ko'rish",
    "detail.empty.title":"Hozircha takliflar yo'q",
    "detail.empty.body":"Bu kategoriya bo'yicha takliflar tez orada qo'shiladi.",
    "head.stat.offers":"Takliflar", "head.stat.bestRate":"Eng yuqori %",
    "head.stat.minEntry":"Eng past kirish", "head.stat.bestDiv":"Eng yuqori dividend",
    "head.stat.bestChange":"Eng yaxshi o'sish",
  },

  ru: {
    "back": "← Категории",
    "detail.offers": "предложений",

    /* ---- deposit ---- */
    "dep.rate":"Годовой %", "dep.term":"Срок", "dep.min":"Мин. сумма",
    "dep.cap":"Капитализация", "dep.early":"Досрочное снятие",
    "dep.online":"Онлайн-открытие", "dep.bank":"Банк", "dep.month":"мес",
    "dep.cap.monthly":"Ежемесячная капитализация", "dep.cap.end":"В конце срока",
    "dep.early.yes":"Досрочно: да", "dep.early.partial":"Досрочно: частично",
    "dep.early.no":"Досрочно: нет",
    "dep.sort.rate.desc":"%: от большего к меньшему", "dep.sort.rate.asc":"%: от меньшего к большему",
    "dep.sort.term.asc":"Срок: от меньшего", "dep.sort.term.desc":"Срок: от большего",
    "dep.sort.min.asc":"Мин. сумма: от меньшей", "dep.sort.min.desc":"Мин. сумма: от большей",
    "dep.tog.cap":"Капитализация", "dep.tog.early":"Досрочное", "dep.tog.online":"Онлайн",
    "dep.tog.all":"Все", "dep.tog.monthly":"Ежемес.", "dep.tog.end":"В конце",
    "dep.tog.yes":"Да", "dep.tog.partial":"Частично", "dep.tog.no":"Нет",
    "dep.filter.bank.all":"Банк: все", "dep.filter.term.all":"Срок: любой",
    "dep.filter.term.6":"Срок: до 6 мес", "dep.filter.term.12":"Срок: до 12 мес",
    "dep.filter.term.24":"Срок: до 24 мес", "dep.filter.term.long":"Срок: более 24 мес",
    "dep.search.ph":"Банк или название депозита…",

    /* ---- stock ---- */
    "stk.price":"Цена", "stk.cap":"Капитализация", "stk.div":"Дивиденды",
    "stk.change":"30 дней", "stk.sector":"Сектор", "stk.liq":"Ликвидность", "stk.ipo":"Новый IPO",
    "stk.sort.div.desc":"Дивиденды: по убыванию", "stk.sort.div.asc":"Дивиденды: по возрастанию",
    "stk.sort.change.desc":"Изм.: по убыванию", "stk.sort.change.asc":"Изм.: по возрастанию",
    "stk.sort.cap.desc":"Капитал.: по убыванию", "stk.sort.cap.asc":"Капитал.: по возрастанию",
    "stk.sort.price.desc":"Цена: по убыванию", "stk.sort.price.asc":"Цена: по возрастанию",
    "stk.filter.sector.all":"Сектор: все", "stk.filter.liq.all":"Ликвидность: любая",
    "stk.filter.div.all":"Дивиденды: любые", "stk.filter.div.yes":"С дивидендами",
    "stk.filter.div.no":"Без дивидендов",
    "stk.tog.dividend":"Дивиденды", "stk.tog.movement":"Движение", "stk.tog.ipo":"Новый IPO",
    "stk.tog.liq":"Ликвидность", "stk.tog.all":"Все", "stk.tog.div.yes":"Есть",
    "stk.tog.div.no":"Нет", "stk.tog.up":"Рост", "stk.tog.down":"Падение",
    "stk.tog.ipo.yes":"Только новые IPO", "stk.tog.liq.hi":"Высокая",
    "stk.tog.liq.mid":"Средняя", "stk.tog.liq.low":"Низкая",
    "stk.search.ph":"Тикер или название компании…",
    "sec.bank":"Банк", "sec.energy":"Энергетика", "sec.metals":"Металлургия",
    "sec.cement":"Цемент", "sec.telecom":"Телеком", "sec.industrial":"Промышл.",
    "sec.chemicals":"Химия", "sec.consumer":"Потреб.", "sec.insurance":"Страхование", "sec.fund":"Фонд",

    /* ---- crypto ---- */
    "crypt.search.ph":"Токен или сеть…",
    "crypt.sort.cap.desc":"Market cap: по убыванию", "crypt.sort.cap.asc":"Market cap: по возрастанию",
    "crypt.sort.price.desc":"Цена: по убыванию", "crypt.sort.price.asc":"Цена: по возрастанию",
    "crypt.sort.change.desc":"30д изм.: по убыванию", "crypt.sort.change.asc":"30д изм.: по возрастанию",
    "crypt.sort.staking.desc":"Staking APY: по убыванию", "crypt.filter.network.all":"Сеть: все",
    "crypt.price":"Цена (USD)", "crypt.cap":"Market cap", "crypt.change":"30 дней",
    "crypt.staking":"Staking APY", "crypt.rank":"Рейтинг", "crypt.network":"Сеть",
    "crypt.tog.staking":"Стейкинг", "crypt.tog.all":"Все",
    "crypt.tog.staking.yes":"Есть", "crypt.tog.staking.no":"Нет",
    "go.crypto":"Смотреть на CoinMarketCap",
    "net.bitcoin":"Bitcoin", "net.ethereum":"Ethereum", "net.bsc":"BNB Chain",
    "net.solana":"Solana", "net.ripple":"Ripple", "net.cardano":"Cardano",
    "net.avalanche":"Avalanche", "net.polkadot":"Polkadot", "net.ton":"TON",
    "head.stat.bestToken":"Лучший рост",

    /* ---- precious metals ---- */
    "metal.search.ph":"Название металла или символ…",
    "metal.sort.price.desc":"Цена: по убыванию", "metal.sort.price.asc":"Цена: по возрастанию",
    "metal.sort.change.desc":"1г изм.: по убыванию", "metal.sort.change.asc":"1г изм.: по возрастанию",
    "metal.filter.cat.all":"Тип: все",
    "metal.price":"Цена (USD)", "metal.change":"1 год", "metal.symbol":"Символ",
    "metal.category":"Тип", "metal.unit.oz":"тр. унц.", "metal.unit.tonne":"тонна",
    "metal.tog.liq":"Ликвидность", "metal.tog.all":"Все",
    "metal.tog.liq.hi":"Высокая", "metal.tog.liq.mid":"Средняя", "metal.tog.liq.low":"Низкая",
    "metal.tog.cat":"Тип", "metal.tog.cat.all":"Все",
    "metal.cat.precious":"Драгоценный металл", "metal.cat.industrial":"Промышленный металл",
    "go.metal":"Подробнее",
    "head.stat.bestMetal":"Лучший рост",

    /* ---- gems ---- */
    "gem.search.ph":"Тип камня или название…",
    "gem.sort.price.desc":"Цена: по убыванию", "gem.sort.price.asc":"Цена: по возрастанию",
    "gem.sort.change.desc":"1г изм.: по убыванию", "gem.sort.change.asc":"1г изм.: по возрастанию",
    "gem.filter.stone.all":"Камень: все",
    "gem.price":"Цена ($/шт.)", "gem.change":"1 год", "gem.stone":"Тип камня",
    "gem.grade":"Качество", "gem.weight":"Вес",
    "gem.tog.liq":"Ликвидность", "gem.tog.all":"Все",
    "gem.tog.liq.hi":"Высокая", "gem.tog.liq.mid":"Средняя", "gem.tog.liq.low":"Низкая",
    "stone.diamond":"Бриллиант (Алмаз)", "stone.ruby":"Рубин",
    "stone.emerald":"Изумруд", "stone.sapphire":"Сапфир",
    "stone.alexandrite":"Александрит", "stone.spinel":"Шпинель",
    "stone.tanzanite":"Танзанит", "stone.tourmaline":"Турмалин (Параиба)",
    "stone.opal":"Чёрный опал",
    "go.gems":"Подробнее",
    "head.stat.bestGem":"Лучший рост",

    /* ---- gaming ---- */
    "skin.search.ph":"Предмет или название игры…",
    "skin.sort.price.desc":"Цена: по убыванию", "skin.sort.price.asc":"Цена: по возрастанию",
    "skin.sort.change.desc":"30д изм.: по убыванию", "skin.sort.change.asc":"30д изм.: по возрастанию",
    "skin.filter.game.all":"Игра: все",
    "skin.price":"Цена в Steam (USD)", "skin.change":"30 дней",
    "skin.game":"Игра", "skin.wear":"Состояние", "skin.float":"Float",
    "skin.tog.game":"Игра", "skin.tog.wear":"Износ", "skin.tog.all":"Все",
    "skin.tog.cs2":"CS2", "skin.tog.other":"Другие",
    "game.cs2":"CS2", "game.dota2":"Dota 2",
    "game.tf2":"TF2", "game.rust":"Rust", "game.pubg":"PUBG",
    "wear.fn":"Factory New", "wear.mw":"Minimal Wear",
    "wear.ft":"Field-Tested", "wear.ww":"Well-Worn", "wear.bs":"Battle-Scarred",
    "go.skin":"Смотреть в Steam Market",
    "head.stat.bestSkin":"Лучший рост",

    /* ---- shared ---- */
    "go.bank":"Открыть на bank.uz", "go.stock":"Посмотреть на uzse.uz",
    "detail.empty.title":"Предложений пока нет",
    "detail.empty.body":"Предложения для этой категории скоро появятся.",
    "head.stat.offers":"Предложений", "head.stat.bestRate":"Макс. %",
    "head.stat.minEntry":"Мин. вход", "head.stat.bestDiv":"Макс. дивиденд",
    "head.stat.bestChange":"Лучший рост",
  },

  en: {
    "back": "← Categories",
    "detail.offers": "offers",

    /* ---- deposit ---- */
    "dep.rate":"Annual rate", "dep.term":"Term", "dep.min":"Min. amount",
    "dep.cap":"Capitalization", "dep.early":"Early withdrawal",
    "dep.online":"Online opening", "dep.bank":"Bank", "dep.month":"mo",
    "dep.cap.monthly":"Monthly compounding", "dep.cap.end":"End of term",
    "dep.early.yes":"Early: yes", "dep.early.partial":"Early: partial", "dep.early.no":"Early: no",
    "dep.sort.rate.desc":"Rate: high to low", "dep.sort.rate.asc":"Rate: low to high",
    "dep.sort.term.asc":"Term: short to long", "dep.sort.term.desc":"Term: long to short",
    "dep.sort.min.asc":"Min. amount: low to high", "dep.sort.min.desc":"Min. amount: high to low",
    "dep.tog.cap":"Compounding", "dep.tog.early":"Early withdrawal", "dep.tog.online":"Online",
    "dep.tog.all":"All", "dep.tog.monthly":"Monthly", "dep.tog.end":"At end",
    "dep.tog.yes":"Yes", "dep.tog.partial":"Partial", "dep.tog.no":"No",
    "dep.filter.bank.all":"Bank: all", "dep.filter.term.all":"Term: any",
    "dep.filter.term.6":"Term: up to 6 mo", "dep.filter.term.12":"Term: up to 12 mo",
    "dep.filter.term.24":"Term: up to 24 mo", "dep.filter.term.long":"Term: 24+ mo",
    "dep.search.ph":"Bank or deposit name…",

    /* ---- stock ---- */
    "stk.price":"Price", "stk.cap":"Market cap", "stk.div":"Dividend",
    "stk.change":"30d", "stk.sector":"Sector", "stk.liq":"Liquidity", "stk.ipo":"Recent IPO",
    "stk.sort.div.desc":"Dividend: high to low", "stk.sort.div.asc":"Dividend: low to high",
    "stk.sort.change.desc":"Change: high to low", "stk.sort.change.asc":"Change: low to high",
    "stk.sort.cap.desc":"Cap: high to low", "stk.sort.cap.asc":"Cap: low to high",
    "stk.sort.price.desc":"Price: high to low", "stk.sort.price.asc":"Price: low to high",
    "stk.filter.sector.all":"Sector: all", "stk.filter.liq.all":"Liquidity: any",
    "stk.filter.div.all":"Dividend: any", "stk.filter.div.yes":"With dividend",
    "stk.filter.div.no":"No dividend",
    "stk.tog.dividend":"Dividend", "stk.tog.movement":"Movement", "stk.tog.ipo":"Recent IPO",
    "stk.tog.liq":"Liquidity", "stk.tog.all":"All", "stk.tog.div.yes":"Yes",
    "stk.tog.div.no":"No", "stk.tog.up":"Up", "stk.tog.down":"Down",
    "stk.tog.ipo.yes":"IPOs only", "stk.tog.liq.hi":"High",
    "stk.tog.liq.mid":"Medium", "stk.tog.liq.low":"Low",
    "stk.search.ph":"Ticker or company…",
    "sec.bank":"Bank", "sec.energy":"Energy", "sec.metals":"Metals",
    "sec.cement":"Cement", "sec.telecom":"Telecom", "sec.industrial":"Industrial",
    "sec.chemicals":"Chemicals", "sec.consumer":"Consumer", "sec.insurance":"Insurance", "sec.fund":"Fund",

    /* ---- crypto ---- */
    "crypt.search.ph":"Token or network…",
    "crypt.sort.cap.desc":"Market cap: high to low", "crypt.sort.cap.asc":"Market cap: low to high",
    "crypt.sort.price.desc":"Price: high to low", "crypt.sort.price.asc":"Price: low to high",
    "crypt.sort.change.desc":"30d change: high to low", "crypt.sort.change.asc":"30d change: low to high",
    "crypt.sort.staking.desc":"Staking APY: high to low", "crypt.filter.network.all":"Network: all",
    "crypt.price":"Price (USD)", "crypt.cap":"Market cap", "crypt.change":"30d",
    "crypt.staking":"Staking APY", "crypt.rank":"Rank", "crypt.network":"Network",
    "crypt.tog.staking":"Staking", "crypt.tog.all":"All",
    "crypt.tog.staking.yes":"Yes", "crypt.tog.staking.no":"No",
    "go.crypto":"View on CoinMarketCap",
    "net.bitcoin":"Bitcoin", "net.ethereum":"Ethereum", "net.bsc":"BNB Chain",
    "net.solana":"Solana", "net.ripple":"Ripple", "net.cardano":"Cardano",
    "net.avalanche":"Avalanche", "net.polkadot":"Polkadot", "net.ton":"TON",
    "head.stat.bestToken":"Best performer",

    /* ---- precious metals ---- */
    "metal.search.ph":"Metal name or symbol…",
    "metal.sort.price.desc":"Price: high to low", "metal.sort.price.asc":"Price: low to high",
    "metal.sort.change.desc":"1yr change: high to low", "metal.sort.change.asc":"1yr change: low to high",
    "metal.filter.cat.all":"Type: all",
    "metal.price":"Price (USD)", "metal.change":"1 year", "metal.symbol":"Symbol",
    "metal.category":"Type", "metal.unit.oz":"troy oz", "metal.unit.tonne":"tonne",
    "metal.tog.liq":"Liquidity", "metal.tog.all":"All",
    "metal.tog.liq.hi":"High", "metal.tog.liq.mid":"Medium", "metal.tog.liq.low":"Low",
    "metal.tog.cat":"Type", "metal.tog.cat.all":"All",
    "metal.cat.precious":"Precious metal", "metal.cat.industrial":"Industrial metal",
    "go.metal":"Learn more",
    "head.stat.bestMetal":"Best performer",

    /* ---- gems ---- */
    "gem.search.ph":"Stone type or name…",
    "gem.sort.price.desc":"Price: high to low", "gem.sort.price.asc":"Price: low to high",
    "gem.sort.change.desc":"1yr change: high to low", "gem.sort.change.asc":"1yr change: low to high",
    "gem.filter.stone.all":"Stone: all",
    "gem.price":"Price ($/pc.)", "gem.change":"1 year", "gem.stone":"Stone type",
    "gem.grade":"Grade", "gem.weight":"Weight",
    "gem.tog.liq":"Liquidity", "gem.tog.all":"All",
    "gem.tog.liq.hi":"High", "gem.tog.liq.mid":"Medium", "gem.tog.liq.low":"Low",
    "stone.diamond":"Diamond (Brilliant)", "stone.ruby":"Ruby",
    "stone.emerald":"Emerald", "stone.sapphire":"Sapphire",
    "stone.alexandrite":"Alexandrite", "stone.spinel":"Spinel",
    "stone.tanzanite":"Tanzanite", "stone.tourmaline":"Paraiba Tourmaline",
    "stone.opal":"Black Opal",
    "go.gems":"Learn more",
    "head.stat.bestGem":"Best performer",

    /* ---- gaming ---- */
    "skin.search.ph":"Item or game name…",
    "skin.sort.price.desc":"Price: high to low", "skin.sort.price.asc":"Price: low to high",
    "skin.sort.change.desc":"30d change: high to low", "skin.sort.change.asc":"30d change: low to high",
    "skin.filter.game.all":"Game: all",
    "skin.price":"Steam price (USD)", "skin.change":"30d",
    "skin.game":"Game", "skin.wear":"Wear", "skin.float":"Float",
    "skin.tog.game":"Game", "skin.tog.wear":"Wear", "skin.tog.all":"All",
    "skin.tog.cs2":"CS2", "skin.tog.other":"Other",
    "game.cs2":"CS2", "game.dota2":"Dota 2",
    "game.tf2":"TF2", "game.rust":"Rust", "game.pubg":"PUBG",
    "wear.fn":"Factory New", "wear.mw":"Minimal Wear",
    "wear.ft":"Field-Tested", "wear.ww":"Well-Worn", "wear.bs":"Battle-Scarred",
    "go.skin":"View on Steam Market",
    "head.stat.bestSkin":"Best performer",

    /* ---- shared ---- */
    "go.bank":"Open on bank.uz", "go.stock":"View on uzse.uz",
    "detail.empty.title":"No offers yet",
    "detail.empty.body":"Offers for this category will be added soon.",
    "head.stat.offers":"Offers", "head.stat.bestRate":"Best rate",
    "head.stat.minEntry":"Lowest entry", "head.stat.bestDiv":"Best dividend",
    "head.stat.bestChange":"Best 30d",
  },
};

window.OFFERS = OFFERS;
window.OFFERS_I18N = OFFERS_I18N;
