/* ============================================================
   INVEST NAVIGATOR — OFFERS DATA
   Per-direction offer lists used by the detail page.
   Sources: bank.uz, uzse.uz (illustrative — figures are
   plausible MVP placeholders, not authoritative quotes).
   ============================================================ */

/* ----------------------------------------------------------
   UZS BANK DEPOSITS — 7 offers
   capitalization: "monthly" | "end"
   earlyWithdrawal: "yes" | "partial" | "no"
   onlineOpen: "yes" | "no"
---------------------------------------------------------- */
const DEPOSIT_UZS_OFFERS = [
  { id: "uzs-asaka-hayot", provider: "Asaka Bank", providerCode: "AS",
    name: { uz: "Hayot depoziti", ru: "Депозит «Хайот»", en: "Hayot deposit" },
    rate: 18, term: 12, minUZS: 1000000,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/asakabank" },
  { id: "uzs-nbu-tezkor", provider: "Milliy Bank (NBU)", providerCode: "NB",
    name: { uz: "Tezkor", ru: "Тезкор", en: "Tezkor" },
    rate: 18, term: 6, minUZS: 500000,
    capitalization: "end", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/nbu" },
  { id: "uzs-agrobank-hosil", provider: "Agrobank", providerCode: "AG",
    name: { uz: "Hosil", ru: "Хосил", en: "Hosil" },
    rate: 21, term: 12, minUZS: 1000000,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/agrobank" },
  { id: "uzs-aloqabank-plus", provider: "Aloqabank", providerCode: "AL",
    name: { uz: "Aloqa Plus", ru: "Алока Плюс", en: "Aloqa Plus" },
    rate: 19, term: 24, minUZS: 5000000,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/aloqabank" },
  { id: "uzs-tbc-online", provider: "TBC Bank UZ", providerCode: "TB",
    name: { uz: "TBC Online", ru: "TBC Онлайн", en: "TBC Online" },
    rate: 21, term: 12, minUZS: 1000000,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/tbc" },
  { id: "uzs-tenge-online", provider: "Tenge Bank", providerCode: "TG",
    name: { uz: "Tenge Online", ru: "Tenge Online", en: "Tenge Online" },
    rate: 18, term: 12, minUZS: 1000000,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/tenge" },
  { id: "uzs-turon-klassik", provider: "Turonbank", providerCode: "TU",
    name: { uz: "Turon Klassik", ru: "Турон Классик", en: "Turon Classic" },
    rate: 18, term: 12, minUZS: 1000000,
    capitalization: "end", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/turonbank" },
];

/* ----------------------------------------------------------
   USD BANK DEPOSITS — 20 offers
---------------------------------------------------------- */
const DEPOSIT_USD_OFFERS = [
  { id: "usd-asaka-valyuta", provider: "Asaka Bank", providerCode: "AS",
    name: { uz: "Valyuta depoziti", ru: "Валютный депозит", en: "FX deposit" },
    rate: 6, term: 24, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/asakabank" },
  { id: "usd-nbu-stabil", provider: "Milliy Bank (NBU)", providerCode: "NB",
    name: { uz: "Stabil USD", ru: "Стабиль USD", en: "Stable USD" },
    rate: 5.5, term: 12, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/nbu" },
  { id: "usd-sqb-investitsiya", provider: "Sanoatqurilishbank", providerCode: "SQ",
    name: { uz: "Investitsiya USD", ru: "Инвестиция USD", en: "Investment USD" },
    rate: 6.5, term: 36, minUSD: 500,
    capitalization: "end", earlyWithdrawal: "no", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/sqb" },
  { id: "usd-ipoteka-omad", provider: "Ipoteka Bank", providerCode: "IP",
    name: { uz: "Omad USD", ru: "Омад USD", en: "Omad USD" },
    rate: 5, term: 12, minUSD: 100,
    capitalization: "end", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/ipoteka" },
  { id: "usd-agrobank-dollar", provider: "Agrobank", providerCode: "AG",
    name: { uz: "Dollar depoziti", ru: "Долларовый депозит", en: "Dollar deposit" },
    rate: 5, term: 12, minUSD: 200,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/agrobank" },
  { id: "usd-aloqa-classic", provider: "Aloqabank", providerCode: "AL",
    name: { uz: "Aloqa Classic", ru: "Алока Classic", en: "Aloqa Classic" },
    rate: 6, term: 24, minUSD: 500,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/aloqabank" },
  { id: "usd-kapital-valyuta", provider: "Kapitalbank", providerCode: "KP",
    name: { uz: "Valyuta", ru: "Валюта", en: "Currency" },
    rate: 5.5, term: 12, minUSD: 100,
    capitalization: "end", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/kapitalbank" },
  { id: "usd-hamkor-dollar", provider: "Hamkorbank", providerCode: "HK",
    name: { uz: "Hamkor Dollar", ru: "Хамкор Доллар", en: "Hamkor Dollar" },
    rate: 5, term: 12, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/hamkorbank" },
  { id: "usd-tbc-online", provider: "TBC Bank UZ", providerCode: "TB",
    name: { uz: "TBC USD", ru: "TBC USD", en: "TBC USD" },
    rate: 6, term: 12, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/tbc" },
  { id: "usd-anor-mobil", provider: "Anorbank", providerCode: "AN",
    name: { uz: "Anor USD", ru: "Анор USD", en: "Anor USD" },
    rate: 6, term: 12, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/anorbank" },
  { id: "usd-infin-smart", provider: "InfinBank", providerCode: "IF",
    name: { uz: "Infin USD", ru: "Infin USD", en: "Infin USD" },
    rate: 4.5, term: 6, minUSD: 300,
    capitalization: "end", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/infinbank" },
  { id: "usd-davr-foiz", provider: "Davrbank", providerCode: "DV",
    name: { uz: "Foiz USD", ru: "Фоиз USD", en: "Foiz USD" },
    rate: 4.5, term: 12, minUSD: 500,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "no",
    url: "https://bank.uz/uz/deposits/davrbank" },
  { id: "usd-trast-omad", provider: "Trastbank", providerCode: "TR",
    name: { uz: "Trast Omad", ru: "Траст Омад", en: "Trast Omad" },
    rate: 5, term: 12, minUSD: 200,
    capitalization: "end", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/trastbank" },
  { id: "usd-saderat-classic", provider: "Saderat Bank", providerCode: "SD",
    name: { uz: "Klassik USD", ru: "Классик USD", en: "Classic USD" },
    rate: 4, term: 12, minUSD: 500,
    capitalization: "monthly", earlyWithdrawal: "no", onlineOpen: "no",
    url: "https://bank.uz/uz/deposits/saderat" },
  { id: "usd-universal-vip", provider: "Universal Bank", providerCode: "UN",
    name: { uz: "Universal VIP", ru: "Universal VIP", en: "Universal VIP" },
    rate: 6.5, term: 36, minUSD: 5000,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/universalbank" },
  { id: "usd-madad-online", provider: "Madad Invest Bank", providerCode: "MD",
    name: { uz: "Madad USD", ru: "Мадад USD", en: "Madad USD" },
    rate: 5, term: 12, minUSD: 200,
    capitalization: "end", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/madadbank" },
  { id: "usd-garant-stabil", provider: "Garant Bank", providerCode: "GR",
    name: { uz: "Garant USD", ru: "Гарант USD", en: "Garant USD" },
    rate: 5.5, term: 24, minUSD: 1000,
    capitalization: "monthly", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/garantbank" },
  { id: "usd-tenge-online", provider: "Tenge Bank", providerCode: "TG",
    name: { uz: "Tenge USD", ru: "Tenge USD", en: "Tenge USD" },
    rate: 6, term: 12, minUSD: 100,
    capitalization: "monthly", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/tenge" },
  { id: "usd-turon-classic", provider: "Turonbank", providerCode: "TU",
    name: { uz: "Turon Dollar", ru: "Турон Доллар", en: "Turon Dollar" },
    rate: 4.5, term: 12, minUSD: 300,
    capitalization: "end", earlyWithdrawal: "partial", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/turonbank" },
  { id: "usd-mikro-plus", provider: "Mikrokreditbank", providerCode: "MK",
    name: { uz: "Mikro USD", ru: "Микро USD", en: "Mikro USD" },
    rate: 5, term: 6, minUSD: 100,
    capitalization: "end", earlyWithdrawal: "yes", onlineOpen: "yes",
    url: "https://bank.uz/uz/deposits/mikrokreditbank" },
];

/* ----------------------------------------------------------
   TSE STOCKS — 20 listings (incl. UZNIF)
   sector: "fund" | "bank" | "energy" | "metals" | "cement" | "telecom" | "industrial" | "chemicals" | "consumer" | "insurance"
   liq: "hi" | "mid" | "low"
   div: yearly dividend yield %
   change30d: % change last 30 days
---------------------------------------------------------- */
const TSE_OFFERS = [
  { id: "tse-uznif", ticker: "UZNIF",
    name: { uz: "O'zbekiston Milliy Investitsiya Fondi", ru: "Узбекский нац. инвест. фонд", en: "Uzbek National Investment Fund" },
    sector: "fund", priceUZS: 1280, marketCapB: 800, divYield: 0, change30d: 8.5,
    liq: "hi", ipo: "2024-12", note: { uz: "Yangi IPO", ru: "Недавний IPO", en: "Recent IPO" },
    url: "https://uzse.uz/issuer/uznif" },
  { id: "tse-kcel", ticker: "KCEL",
    name: { uz: "Kvarts (keramika)", ru: "Кварц (керамика)", en: "Kvarts (ceramics)" },
    sector: "industrial", priceUZS: 18500, marketCapB: 320, divYield: 4.5, change30d: 3.2,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/kcel" },
  { id: "tse-hmkb", ticker: "HMKB",
    name: { uz: "Hamkorbank", ru: "Хамкорбанк", en: "Hamkorbank" },
    sector: "bank", priceUZS: 1450, marketCapB: 2400, divYield: 6.2, change30d: 5.8,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/hmkb" },
  { id: "tse-sqbn", ticker: "SQBN",
    name: { uz: "Sanoatqurilishbank", ru: "Саноаткурилишбанк", en: "Sanoatqurilishbank" },
    sector: "bank", priceUZS: 980, marketCapB: 1850, divYield: 5.5, change30d: 2.1,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/sqbn" },
  { id: "tse-agbn", ticker: "AGBN",
    name: { uz: "Agrobank", ru: "Агробанк", en: "Agrobank" },
    sector: "bank", priceUZS: 720, marketCapB: 980, divYield: 4.8, change30d: 1.4,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/agbn" },
  { id: "tse-iptb", ticker: "IPTB",
    name: { uz: "Ipoteka Bank", ru: "Ипотека Банк", en: "Ipoteka Bank" },
    sector: "bank", priceUZS: 1180, marketCapB: 1320, divYield: 5.0, change30d: 3.6,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/iptb" },
  { id: "tse-umkk", ticker: "UMKK",
    name: { uz: "O'zmetkombinat", ru: "Узметкомбинат", en: "Uzmetkombinat" },
    sector: "metals", priceUZS: 4200, marketCapB: 540, divYield: 7.2, change30d: -2.5,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/umkk" },
  { id: "tse-kscm", ticker: "KSCM",
    name: { uz: "Quvasoy Sement", ru: "Кувасайцемент", en: "Quvasoy Cement" },
    sector: "cement", priceUZS: 8800, marketCapB: 210, divYield: 5.8, change30d: 4.1,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/kscm" },
  { id: "tse-qzsm", ticker: "QZSM",
    name: { uz: "Qizilqumsement", ru: "Кызылкумцемент", en: "Qizilqumsement" },
    sector: "cement", priceUZS: 12400, marketCapB: 380, divYield: 6.5, change30d: 2.8,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/qzsm" },
  { id: "tse-ungp", ticker: "UNGP",
    name: { uz: "O'zbekneftegaz", ru: "Узбекнефтегаз", en: "Uzbekneftegaz" },
    sector: "energy", priceUZS: 6200, marketCapB: 1620, divYield: 8.0, change30d: 6.4,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/ungp" },
  { id: "tse-agmk", ticker: "AGMK",
    name: { uz: "Olmaliq KMK", ru: "Алмалыкский ГМК", en: "Almalyk MMC" },
    sector: "metals", priceUZS: 24500, marketCapB: 2890, divYield: 9.2, change30d: 11.3,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/agmk" },
  { id: "tse-uzrt", ticker: "UZRT",
    name: { uz: "O'zbektelekom", ru: "Узбектелеком", en: "Uzbektelecom" },
    sector: "telecom", priceUZS: 3850, marketCapB: 720, divYield: 5.5, change30d: 1.8,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/uzrt" },
  { id: "tse-uzin", ticker: "UZIN",
    name: { uz: "O'zbekinvest sug'urta", ru: "Узбекинвест", en: "Uzbekinvest insurance" },
    sector: "insurance", priceUZS: 950, marketCapB: 145, divYield: 4.2, change30d: -1.1,
    liq: "low", ipo: null, url: "https://uzse.uz/issuer/uzin" },
  { id: "tse-tklz", ticker: "TKLZ",
    name: { uz: "Toshkentlift", ru: "Ташкентлифт", en: "Tashkentlift" },
    sector: "industrial", priceUZS: 5400, marketCapB: 78, divYield: 3.0, change30d: 0.6,
    liq: "low", ipo: null, url: "https://uzse.uz/issuer/tklz" },
  { id: "tse-uzpb", ticker: "UZPB",
    name: { uz: "O'zfarmsanoat", ru: "Узфармсаноат", en: "Uzpharmsanoat" },
    sector: "consumer", priceUZS: 2150, marketCapB: 165, divYield: 4.5, change30d: 2.2,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/uzpb" },
  { id: "tse-chrg", ticker: "CHRG",
    name: { uz: "Chirchiq Kimyo", ru: "Чирчик Кимё", en: "Chirchiq Chemicals" },
    sector: "chemicals", priceUZS: 14200, marketCapB: 410, divYield: 6.8, change30d: 5.2,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/chrg" },
  { id: "tse-uzau", ticker: "UZAU",
    name: { uz: "Navoiy KMK", ru: "Навоийский ГМК", en: "Navoi MMC" },
    sector: "metals", priceUZS: 38500, marketCapB: 4250, divYield: 10.5, change30d: 14.2,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/uzau" },
  { id: "tse-tkvs", ticker: "TKVS",
    name: { uz: "Toshkent Vino Kombinati", ru: "Ташкентский винкомбинат", en: "Tashkent Wine" },
    sector: "consumer", priceUZS: 7600, marketCapB: 95, divYield: 4.0, change30d: 0.9,
    liq: "low", ipo: null, url: "https://uzse.uz/issuer/tkvs" },
  { id: "tse-asbt", ticker: "ASBT",
    name: { uz: "Asaka Bank", ru: "Асака Банк", en: "Asaka Bank" },
    sector: "bank", priceUZS: 2100, marketCapB: 1980, divYield: 5.2, change30d: 4.4,
    liq: "hi", ipo: null, url: "https://uzse.uz/issuer/asbt" },
  { id: "tse-uzav", ticker: "UZAV",
    name: { uz: "O'zavtosanoat", ru: "Узавтосаноат", en: "Uzavtosanoat" },
    sector: "industrial", priceUZS: 4850, marketCapB: 620, divYield: 6.0, change30d: 3.7,
    liq: "mid", ipo: null, url: "https://uzse.uz/issuer/uzav" },
];

/* ----------------------------------------------------------
   REGISTRY — which directions have offers
---------------------------------------------------------- */
const OFFERS = {
  "deposit-uzs": { kind: "deposit", currency: "UZS", items: DEPOSIT_UZS_OFFERS },
  "deposit-usd": { kind: "deposit", currency: "USD", items: DEPOSIT_USD_OFFERS },
  "tse":         { kind: "stock",   currency: "UZS", items: TSE_OFFERS },
};

/* ----------------------------------------------------------
   I18N additions for offers
---------------------------------------------------------- */
const OFFERS_I18N = {
  uz: {
    "back": "← Yo'nalishlar",
    "detail.offers": "ta taklif",

    // deposit-specific
    "dep.rate":  "Yillik foiz",
    "dep.term":  "Muddat",
    "dep.min":   "Min. summa",
    "dep.cap":   "Kapitalizatsiya",
    "dep.early": "Muddatdan oldin yechib olish",
    "dep.online": "Online ochish",
    "dep.bank":  "Bank",
    "dep.month": "oy",
    "dep.cap.monthly": "Oylik kapitalizatsiya",
    "dep.cap.end":     "Muddat oxirida",
    "dep.early.yes":     "Erta yechib olish: ha",
    "dep.early.partial": "Erta yechib olish: qisman",
    "dep.early.no":      "Erta yechib olish: yo'q",

    "dep.sort.rate.desc": "Foiz: yuqoridan pastga",
    "dep.sort.rate.asc":  "Foiz: pastdan yuqoriga",
    "dep.sort.term.asc":  "Muddat: qisqadan uzunga",
    "dep.sort.term.desc": "Muddat: uzundan qisqaga",
    "dep.sort.min.asc":   "Min. summa: kichikdan kattaga",
    "dep.sort.min.desc":  "Min. summa: kattadan kichikka",

    "dep.tog.cap":     "Kapitalizatsiya",
    "dep.tog.early":   "Erta yechish",
    "dep.tog.online":  "Online ochish",
    "dep.tog.all":     "Barchasi",
    "dep.tog.monthly": "Oylik",
    "dep.tog.end":     "Oxirida",
    "dep.tog.yes":     "Ha",
    "dep.tog.partial": "Qisman",
    "dep.tog.no":      "Yo'q",

    "dep.filter.bank.all": "Bank: barchasi",
    "dep.filter.term.all": "Muddat: har qanday",
    "dep.filter.term.6":   "Muddat: 6 oygacha",
    "dep.filter.term.12":  "Muddat: 12 oygacha",
    "dep.filter.term.24":  "Muddat: 24 oygacha",
    "dep.filter.term.long":"Muddat: 24 oydan ko'p",

    "dep.search.ph": "Bank yoki depozit nomi\u2026",

    // stock-specific
    "stk.price":  "Narx",
    "stk.cap":    "Bozor kapital",
    "stk.div":    "Dividend",
    "stk.change": "30 kun",
    "stk.sector": "Tarmoq",
    "stk.liq":    "Likvidlik",
    "stk.ipo":    "Yangi IPO",

    "stk.sort.div.desc":    "Dividend: yuqoridan pastga",
    "stk.sort.div.asc":     "Dividend: pastdan yuqoriga",
    "stk.sort.change.desc": "O'zgarish: yuqoridan pastga",
    "stk.sort.change.asc":  "O'zgarish: pastdan yuqoriga",
    "stk.sort.cap.desc":    "Kapital: kattadan kichikka",
    "stk.sort.cap.asc":     "Kapital: kichikdan kattaga",
    "stk.sort.price.desc":  "Narx: yuqoridan pastga",
    "stk.sort.price.asc":   "Narx: pastdan yuqoriga",

    "stk.filter.sector.all": "Tarmoq: barchasi",
    "stk.filter.liq.all":    "Likvidlik: har qanday",
    "stk.filter.div.all":    "Dividend: har qanday",
    "stk.filter.div.yes":    "Dividend bor",
    "stk.filter.div.no":     "Dividendsiz",

    "stk.tog.dividend": "Dividend",
    "stk.tog.movement": "Harakat",
    "stk.tog.ipo":      "Yangi IPO",
    "stk.tog.liq":      "Likvidlik",
    "stk.tog.all":      "Barchasi",
    "stk.tog.div.yes":  "Bor",
    "stk.tog.div.no":   "Yo'q",
    "stk.tog.up":       "O'sgan",
    "stk.tog.down":     "Tushgan",
    "stk.tog.ipo.yes":  "Faqat yangi IPO",
    "stk.tog.liq.hi":   "Yuqori",
    "stk.tog.liq.mid":  "O'rta",
    "stk.tog.liq.low":  "Past",

    "stk.search.ph": "Tiker yoki kompaniya nomi\u2026",

    // sector labels
    "sec.bank":       "Bank",
    "sec.energy":     "Energetika",
    "sec.metals":     "Metallurgiya",
    "sec.cement":     "Sement",
    "sec.telecom":    "Telekom",
    "sec.industrial": "Sanoat",
    "sec.chemicals":  "Kimyo",
    "sec.consumer":   "Iste'mol",
    "sec.insurance":  "Sug'urta",
    "sec.fund":       "Fond",

    "go.bank": "bank.uz da ochish",
    "go.stock": "uzse.uz da ko'rish",

    "detail.empty.title": "Hozircha takliflar yo'q",
    "detail.empty.body":  "Bu yo'nalish bo'yicha takliflar tez orada qo'shiladi.",

    // live stats for offers page
    "head.stat.offers":   "Takliflar",
    "head.stat.bestRate": "Eng yuqori %",
    "head.stat.minEntry": "Eng past kirish",
    "head.stat.bestDiv":  "Eng yuqori dividend",
    "head.stat.bestChange":"Eng yaxshi o'sish",
  },
  ru: {
    "back": "← Направления",
    "detail.offers": "предложений",

    "dep.rate":  "Годовой %",
    "dep.term":  "Срок",
    "dep.min":   "Мин. сумма",
    "dep.cap":   "Капитализация",
    "dep.early": "Досрочное снятие",
    "dep.online": "Онлайн-открытие",
    "dep.bank":  "Банк",
    "dep.month": "мес",
    "dep.cap.monthly": "Ежемесячная капитализация",
    "dep.cap.end":     "В конце срока",
    "dep.early.yes":     "Досрочно: да",
    "dep.early.partial": "Досрочно: частично",
    "dep.early.no":      "Досрочно: нет",

    "dep.sort.rate.desc": "%: от большего к меньшему",
    "dep.sort.rate.asc":  "%: от меньшего к большему",
    "dep.sort.term.asc":  "Срок: от меньшего",
    "dep.sort.term.desc": "Срок: от большего",
    "dep.sort.min.asc":   "Мин. сумма: от меньшей",
    "dep.sort.min.desc":  "Мин. сумма: от большей",

    "dep.tog.cap":     "Капитализация",
    "dep.tog.early":   "Досрочное",
    "dep.tog.online":  "Онлайн",
    "dep.tog.all":     "Все",
    "dep.tog.monthly": "Ежемес.",
    "dep.tog.end":     "В конце",
    "dep.tog.yes":     "Да",
    "dep.tog.partial": "Частично",
    "dep.tog.no":      "Нет",

    "dep.filter.bank.all": "Банк: все",
    "dep.filter.term.all": "Срок: любой",
    "dep.filter.term.6":   "Срок: до 6 мес",
    "dep.filter.term.12":  "Срок: до 12 мес",
    "dep.filter.term.24":  "Срок: до 24 мес",
    "dep.filter.term.long":"Срок: более 24 мес",

    "dep.search.ph": "Банк или название депозита\u2026",

    "stk.price":  "Цена",
    "stk.cap":    "Капитализация",
    "stk.div":    "Дивиденды",
    "stk.change": "30 дней",
    "stk.sector": "Сектор",
    "stk.liq":    "Ликвидность",
    "stk.ipo":    "Новый IPO",

    "stk.sort.div.desc":    "Дивиденды: по убыванию",
    "stk.sort.div.asc":     "Дивиденды: по возрастанию",
    "stk.sort.change.desc": "Изм.: по убыванию",
    "stk.sort.change.asc":  "Изм.: по возрастанию",
    "stk.sort.cap.desc":    "Капитал.: по убыванию",
    "stk.sort.cap.asc":     "Капитал.: по возрастанию",
    "stk.sort.price.desc":  "Цена: по убыванию",
    "stk.sort.price.asc":   "Цена: по возрастанию",

    "stk.filter.sector.all": "Сектор: все",
    "stk.filter.liq.all":    "Ликвидность: любая",
    "stk.filter.div.all":    "Дивиденды: любые",
    "stk.filter.div.yes":    "С дивидендами",
    "stk.filter.div.no":     "Без дивидендов",

    "stk.tog.dividend": "Дивиденды",
    "stk.tog.movement": "Движение",
    "stk.tog.ipo":      "Новый IPO",
    "stk.tog.liq":      "Ликвидность",
    "stk.tog.all":      "Все",
    "stk.tog.div.yes":  "Есть",
    "stk.tog.div.no":   "Нет",
    "stk.tog.up":       "Рост",
    "stk.tog.down":     "Падение",
    "stk.tog.ipo.yes":  "Только новые IPO",
    "stk.tog.liq.hi":   "Высокая",
    "stk.tog.liq.mid":  "Средняя",
    "stk.tog.liq.low":  "Низкая",

    "stk.search.ph": "Тикер или название компании\u2026",

    "sec.bank":       "Банк",
    "sec.energy":     "Энергетика",
    "sec.metals":     "Металлургия",
    "sec.cement":     "Цемент",
    "sec.telecom":    "Телеком",
    "sec.industrial": "Промышл.",
    "sec.chemicals":  "Химия",
    "sec.consumer":   "Потреб.",
    "sec.insurance":  "Страхование",
    "sec.fund":       "Фонд",

    "go.bank": "Открыть на bank.uz",
    "go.stock": "Посмотреть на uzse.uz",

    "detail.empty.title": "Предложений пока нет",
    "detail.empty.body":  "Предложения для этого направления скоро появятся.",

    "head.stat.offers":   "Предложений",
    "head.stat.bestRate": "Макс. %",
    "head.stat.minEntry": "Мин. вход",
    "head.stat.bestDiv":  "Макс. дивиденд",
    "head.stat.bestChange":"Лучший рост",
  },
  en: {
    "back": "← Directions",
    "detail.offers": "offers",

    "dep.rate":  "Annual rate",
    "dep.term":  "Term",
    "dep.min":   "Min. amount",
    "dep.cap":   "Capitalization",
    "dep.early": "Early withdrawal",
    "dep.online": "Online opening",
    "dep.bank":  "Bank",
    "dep.month": "mo",
    "dep.cap.monthly": "Monthly compounding",
    "dep.cap.end":     "End of term",
    "dep.early.yes":     "Early: yes",
    "dep.early.partial": "Early: partial",
    "dep.early.no":      "Early: no",

    "dep.sort.rate.desc": "Rate: high to low",
    "dep.sort.rate.asc":  "Rate: low to high",
    "dep.sort.term.asc":  "Term: short to long",
    "dep.sort.term.desc": "Term: long to short",
    "dep.sort.min.asc":   "Min. amount: low to high",
    "dep.sort.min.desc":  "Min. amount: high to low",

    "dep.tog.cap":     "Compounding",
    "dep.tog.early":   "Early withdrawal",
    "dep.tog.online":  "Online",
    "dep.tog.all":     "All",
    "dep.tog.monthly": "Monthly",
    "dep.tog.end":     "At end",
    "dep.tog.yes":     "Yes",
    "dep.tog.partial": "Partial",
    "dep.tog.no":      "No",

    "dep.filter.bank.all": "Bank: all",
    "dep.filter.term.all": "Term: any",
    "dep.filter.term.6":   "Term: up to 6 mo",
    "dep.filter.term.12":  "Term: up to 12 mo",
    "dep.filter.term.24":  "Term: up to 24 mo",
    "dep.filter.term.long":"Term: 24+ mo",

    "dep.search.ph": "Bank or deposit name\u2026",

    "stk.price":  "Price",
    "stk.cap":    "Market cap",
    "stk.div":    "Dividend",
    "stk.change": "30d",
    "stk.sector": "Sector",
    "stk.liq":    "Liquidity",
    "stk.ipo":    "Recent IPO",

    "stk.sort.div.desc":    "Dividend: high to low",
    "stk.sort.div.asc":     "Dividend: low to high",
    "stk.sort.change.desc": "Change: high to low",
    "stk.sort.change.asc":  "Change: low to high",
    "stk.sort.cap.desc":    "Cap: high to low",
    "stk.sort.cap.asc":     "Cap: low to high",
    "stk.sort.price.desc":  "Price: high to low",
    "stk.sort.price.asc":   "Price: low to high",

    "stk.filter.sector.all": "Sector: all",
    "stk.filter.liq.all":    "Liquidity: any",
    "stk.filter.div.all":    "Dividend: any",
    "stk.filter.div.yes":    "With dividend",
    "stk.filter.div.no":     "No dividend",

    "stk.tog.dividend": "Dividend",
    "stk.tog.movement": "Movement",
    "stk.tog.ipo":      "Recent IPO",
    "stk.tog.liq":      "Liquidity",
    "stk.tog.all":      "All",
    "stk.tog.div.yes":  "Yes",
    "stk.tog.div.no":   "No",
    "stk.tog.up":       "Up",
    "stk.tog.down":     "Down",
    "stk.tog.ipo.yes":  "IPOs only",
    "stk.tog.liq.hi":   "High",
    "stk.tog.liq.mid":  "Medium",
    "stk.tog.liq.low":  "Low",

    "stk.search.ph": "Ticker or company\u2026",

    "sec.bank":       "Bank",
    "sec.energy":     "Energy",
    "sec.metals":     "Metals",
    "sec.cement":     "Cement",
    "sec.telecom":    "Telecom",
    "sec.industrial": "Industrial",
    "sec.chemicals":  "Chemicals",
    "sec.consumer":   "Consumer",
    "sec.insurance":  "Insurance",
    "sec.fund":       "Fund",

    "go.bank": "Open on bank.uz",
    "go.stock": "View on uzse.uz",

    "detail.empty.title": "No offers yet",
    "detail.empty.body":  "Offers for this direction will be added soon.",

    "head.stat.offers":   "Offers",
    "head.stat.bestRate": "Best rate",
    "head.stat.minEntry": "Lowest entry",
    "head.stat.bestDiv":  "Best dividend",
    "head.stat.bestChange":"Best 30d",
  },
};

window.OFFERS = OFFERS;
window.OFFERS_I18N = OFFERS_I18N;
